% -------------------------------------------------------------------------
% collect_moments.m: collect moments for tables across simulations
% -------------------------------------------------------------------------
% authors:         Rohan Kekre and Moritz Lenel
% for updates see: https://github.com/KekreLenel/safety
% -------------------------------------------------------------------------

%% Average moments for tables 

    table_2_moms(:,ccc)  = mean(table_2_moms_tmp, 2);
    table_3_moms(:,ccc)  = mean(table_3_moms_tmp, 2);
    table_4_moms(:,ccc)  = mean(table_4_moms_tmp, 2);
    table_5_moms(:,ccc)  = mean(table_5_moms_tmp, 2);
    table_6_moms(:,ccc)  = mean(table_6_moms_tmp, 2);
    table_7_moms(:,ccc)  = mean(table_7_moms_tmp, 2);
    table_7_moms(:,ccc)  = mean(table_7_moms_tmp, 2);
    table_7_moms(:,ccc)  = 100*table_7_moms(:,ccc)/sum(table_7_moms([1,2,6],ccc));
    table_10_moms(:,ccc) = mean(table_10_moms_tmp, 2);

%% Store parameters for calibration tables

        table_1_params(:,ccc) = [   ...
                            trg_prms.ies_h, ...
                            trg_prms.sigma, ...
                            trg_prms.varsigma_h - 1/(1 + trg_prms.zeta), ...
                            trg_prms.chi, ...
                            trg_prms.aalpha, ...
                            trg_prms.delta, ...
                            trg_prms.vareps_w, ...
                            trg_prms.varphi_w, ...
                            trg_prms.phi_pi_h, ...
                            -trg_prms.disast_shock, ...
                            100*exp(trg_prms.disast_p), ...
                            trg_prms.p_rho, ...
                            sig_dis, ...
                            exp(trg_prms.omg_mean), ...
                            trg_prms.omg_rho, ...
                            trg_prms.corr_omg_dis
                          ];        

        table_2_params(:,ccc) = [   ...
                            trg_prms.zeta, ...
                            trg_prms.sig_z, ...
                            trg_prms.std_zf*sqrt(1-trg_prms.rho_zf^2), ...
                            trg_prms.rho_zf, ...
                            trg_prms.chiX, ...
                            trg_prms.bbeta_f, ...
                            trg_prms.bbeta_h, ...
                            sig_omg, ...
                            trg_prms.gma_f, ...
                            trg_prms.gma_h, ...
                            trg_prms.bg_yss, ...
                            chi0_vec(1), ...
                            chi0_vec(2), ...
                            100*trg_prms.tayl_ic_h, ...
                            100*trg_prms.tayl_ic_f
                          ];        
% 
