% -------------------------------------------------------------------------
% create_tables.m: creates tables for main text and appendix 
% -------------------------------------------------------------------------
% authors:         Rohan Kekre and Moritz Lenel
% for updates see: https://github.com/KekreLenel/safety
% -------------------------------------------------------------------------

%% Table 1: external parameters

    string_list = [ ...
    "$\\psi$ & IES & %.2f & \\\\ \n", ...
    "$\\sigma$ & trade elasticity & %.1f & \\cite{backusetal1994} \\\\ \n", ...
    "$\\varsigma$ & home bias & %.1f & \\cite{eatonetal2016} \\\\ \n", ...
    "$\\nu$ & Frisch elasticity & %.2f & \\cite{chettyetal2011} \\\\ \n", ...
    "$\\alpha$ & 1 - labor share & %.2f & \\\\ \n", ...
    "$\\delta$ & depreciation rate & %.3f & \\\\ \n", ...
    "$\\epsilon$ & elast. of subs. across workers & %.0f \\\\ \n", ...
    "$\\chi^{W}$ & Rotemberg wage adj. costs & %.0f & $\\approx \\mathbb{P}(\\mbox{adjust}) = 5 \\enspace \\mbox{qtrs}$ \\\\ \n", ...
    "$\\phi^\\pi$ & Taylor coeff. on inflation & %.1f & \\cite{taylor1993}  \\\\ \n", ...
    "$\\underline{\\varphi}$ & disaster shock & %.2f & \\cite{nakamuraetal2013} \\\\ \n", ...
    "$p$ & disaster risk & %.1f\\%% & $E[p] = 0.5\\%%$ (\\cite{barro2006}) \\\\ \n", ...
    "$\\rho^p$ & dis. risk persistence & %.2f & $\\rho(p) = 0.7$ \\\\ \n", ...
    "$\\sigma^p$ & dis. risk std. dev. & %.2f & $\\sigma(p)/E[p] = 1$ \\\\ \n", ...
    "$\\omega^d$ & safety skewness & %.3f & $skew(\\omega) = 6.1$ \\\\\n", ...
    "$\\rho^{\\omega}$ & safety persistence & %.1f & $\\rho(\\omega) = 0.3$ \\\\ \n", ...
    "$\\rho^{p\\omega}$ & corr. safety, disaster & %.1f & $\\rho(p,\\omega) = 0.4$ \\\\ \\hline \n", ...
    ];
    
    % Write Targeted Moments
    comp_idxs = [ix_bm];
    loc_fileID = fopen([tab_path, '/table_1.tex'],'w');
    fprintf(loc_fileID, "& Description & Value & Notes \\\\ \\hline\n" ); 
    for rrr = 1:size(string_list,2)
    fprintf(loc_fileID, string_list(rrr), table_1_params(rrr,comp_idxs));
    end
    fprintf(loc_fileID, "\\hline \n");
    fclose(loc_fileID);


%% Table 2: targeted moments

    % Parameters
    param_names  = [ ...
                    "$\zeta^*$        ",...
                    "$\sigma^z$       ",...
                    "$\sigma^{F}$     ",...
                    "$\rho^{F}$       ",...
                    "$\chi^x$         ",...
                    "$\beta^*$        ",...
                    "$\beta$          ",...
                    "$\sigma^{\omega}$",...
                    "$\gamma^*$       ",...
                    "$\gamma$        ",...
                    "$\bar{b}^g$     ",...
                    "$\bar{\nu}$      ",...
                    "$\bar{\nu}^*$    " ...
                    "$\bar{i}$    " ...
                    "$\bar{i}^*$    " ...
                  ];


    param_desc     = [ ...
                    "rel. pop.           ", ...
                    "std. dev. prod.     ", ...
                    "std. dev. rel. prod.", ...
                    "persist. rel. prod. ", ...
                    "capital adj cost    ", ...
                    "disc. fac. Foreign  ", ...
                    "disc. fac. Home     ", ...
                    "std. dev. safety    ", ...
                    "RRA Foreign         ", ...
                    "RRA Home            ", ...
                    "safe debt/agg. cons.", ...
                    "$\ell$ disutility   ", ...
                    "$\ell^*$ disutility "  ...
                    "Taylor intercept Home"  ...
                    "Taylor intercept Foreign"  ...
                  ]; 

    targeted_names  = [ ...
                    "$y^*/(sy)$                                          ",...
                    "$\sigma(\Delta \log c)$                             ",...
                    "$\sigma(\Delta\log y^*)$                            ",...
                    "$\rho(y^*/y,y_{-4}^*/y_{-4})$                       ",...
                    "$\sigma(\Delta \log x)$                             ",...
                    "$4 \mathbb{E} r$                                    ",...
                    "$nfa/(4y)$                                          ",...
                    "$\rho_{-1}\left(r^e,r^* + \Delta \log q - r\right)$ ",...
                    "$4 \mathbb{E} \left[r^e - r \right]$                ",...
                    "$\beta((\Delta nfa)/y,r^e - r)$                     ",...
                    "$b_{H,s}^*/(4y)$                                    ",...
                    "$\ell$                                              ",...
                    "$\ell^*$                                            ",...    
                    "$\log P/P_{-1}$                                          ",...    
                    "$\log P^*/P^*_{-1}$                                       "    
                  ];

    % moment Targets
    targeted_values = [ ... 
                    "1.6", ...
                    "0.5", ...
                    "0.8", ...
                    "0.6", ...
                    "1.6", ...
                    "2.0", ...
                    "-23", ...
                    "0.5", ...
                    "5.1", ...
                    "0.5", ...
                    "3.8", ...
                    "1  ", ...
                    "1  " ...
                    "0", ...
                    "0"
                    ];
               
    string_list = [ "%s & %s & %.1f & %s & %.1f     & %.1f     \\\\ \n", ... 
                    "%s & %s & %.3f & %s & %.1f\\%% & %.1f\\%% \\\\ \n", ... 
                    "%s & %s & %.3f & %s & %.1f\\%% & %.1f\\%% \\\\ \n", ... 
                    "%s & %s & %.1f & %s & %.1f     & %.1f     \\\\ \n", ... 
                    "%s & %s & %.0f & %s & %.1f\\%% & %.1f\\%% \\\\ \n", ... 
                    "%s & %s & %.4f & %s & %.1f\\%% & %.1f\\%% \\\\ \n", ... 
                    "%s & %s & %.4f & %s & %.0f\\%% & %.0f\\%% \\\\ \n", ... 
                    "%s & %s & %.2f & %s & %.1f & %.1f \\\\ \n", ... 
                    "%s & %s & %.0f & %s & %.1f\\%% & %.1f\\%% \\\\ \n", ... 
                    "%s & %s & %.0f & %s & %.1f & %.1f \\\\ \n", ... 
                    "%s & %s & %.3f & %s & %.1f\\%% & %.1f\\%% \\\\ \n", ... 
                    "%s & %s & %.2f & %s & %.0f     & %.1f     \\\\ \n", ... 
                    "%s & %s & %.2f & %s & %.0f     & %.1f     \\\\ \n", ...
                    "%s & %s & %.2f\\%% & %s & %.1f\\%% & %.1f\\%% \\\\ \n", ... 
                    "%s & %s & %.2f\\%% & %s & %.1f\\%% & %.1f\\%% \\\\ \n" 
                    ];
                    
    comp_idxs = [ix_bm];
    loc_fileID = fopen([tab_path, '/table_2.tex'],'w');
    fprintf(loc_fileID, "& Description & Value & Moment & Target & Model   \\\\ \n");
    fprintf(loc_fileID, "\\hline \n");
    for rrr = 1:size(string_list,2)
    fprintf(loc_fileID, string_list(rrr), param_names(rrr), param_desc(rrr), table_2_params(rrr,comp_idxs), targeted_names(rrr),  targeted_values(rrr),  table_2_moms(rrr,comp_idxs));
    end
    fprintf(loc_fileID, "\\hline \n");
    fclose(loc_fileID);


%% Table 3: comovements in the international monetary system

    % Moment Names
    comp_idxs = [ix_bm,ix_no_omg,ix_symm];
    names_vec = [   "$\beta(r_{t+1}^* - \Delta \log q_{t+1} - r_{t+1},\log y_t - \log y_{t-4})$", ...
                    "$\beta(r_{t+1}^* - \Delta \log q_{t+1} - r_{t+1},r_{t+1}^e)$", ...
                    "$\beta((\Delta nfa_{t+1})/y_t,r_{t+1}^* - \Delta \log q_{t+1} - r_{t+1})$", ...
                    "\emph{Memo}: $(k-\kappa)/(4y)$", ...
                    "\hspace{1.25cm} $b_H/(4y)$", ...
                    "\hspace{1.25cm} $b_F/(4y)$"
                    ];

    % Data Values
    data_vec = [ -0.17, 0.23, 1.38 ];
      
    % Write Unargeted Moments
    loc_fileID = fopen([tab_path, '/table_3.tex'],'w');
    fprintf(loc_fileID, "  & Data & Model & No $\\omega$ & $\\gamma=\\gamma^\\ast$ \\\\ \n");
    fprintf(loc_fileID, "\\hline \n");
    fprintf(loc_fileID, "%s & $%6.2f$ & $%6.2f$ & $%6.2f$ & $%6.2f$ \\\\ \n", names_vec(1),  data_vec(1), table_3_moms(1,comp_idxs));
    fprintf(loc_fileID, "& (0.11) & & & \\\\ \n");
    fprintf(loc_fileID, "%s & $%6.2f$ & $%6.2f$ & $%6.2f$ & $%6.2f$ \\\\ \n", names_vec(2),  data_vec(2), table_3_moms(2,comp_idxs));
    fprintf(loc_fileID, "& (0.04) & & & \\\\ \n");
    fprintf(loc_fileID, "%s & $%6.2f$ & $%6.2f$ & $%6.2f$ & $%6.2f$ \\\\ \n"    , names_vec(3),  data_vec(3), table_3_moms(3,comp_idxs));
    fprintf(loc_fileID, "& (0.30) & & & \\\\ \\hline \n");
    fprintf(loc_fileID, "%s &  & $%6.1f\\%%$ & $%6.1f\\%%$ & $%6.1f\\%%$ \\\\ \n", names_vec(4), table_3_moms(4,comp_idxs));
    fprintf(loc_fileID, "%s & & $%6.1f\\%%$ & $%6.1f\\%%$ & $%6.1f\\%%$ \\\\ \n", names_vec(5),  table_3_moms(5,comp_idxs));
    fprintf(loc_fileID, "%s &  & $%6.1f\\%%$ & $%6.1f\\%%$ & $%6.1f\\%%$ \\\\ \n", names_vec(6),   table_3_moms(6,comp_idxs));
    fprintf(loc_fileID, "\\hline \n");
    fclose(loc_fileID);

    % Write Unargeted Moments
    comp_idxs = [ix_bm,ix_tayl_y0,ix_tayl_rho];
    loc_fileID = fopen([tab_path, '/table_9.tex'],'w');
    fprintf(loc_fileID, "  & Model & $\\phi^y=0.5/4$ & $\\phi^y=0.5/4$, $\\rho^i=0.5$\\\\ \n");
    fprintf(loc_fileID, "\\hline \n");
    fprintf(loc_fileID, "%s & $%6.2f$ & $%6.2f$ & $%6.2f$ \\\\ \n", names_vec(1),  table_3_moms(1,comp_idxs));
    fprintf(loc_fileID, "%s & $%6.2f$ & $%6.2f$ & $%6.2f$ \\\\ \n", names_vec(2),  table_3_moms(2,comp_idxs));
    fprintf(loc_fileID, "%s & $%6.2f$ & $%6.2f$ & $%6.2f$ \\\\ \\hline \n"    , names_vec(3),  table_3_moms(3,comp_idxs));
    fprintf(loc_fileID, "%s & $%6.1f\\%%$ & $%6.1f\\%%$ & $%6.1f\\%%$ \\\\ \n", names_vec(4), table_3_moms(4,comp_idxs));
    fprintf(loc_fileID, "%s & $%6.1f\\%%$ & $%6.1f\\%%$ & $%6.1f\\%%$ \\\\ \n", names_vec(5),  table_3_moms(5,comp_idxs));
    fprintf(loc_fileID, "%s & $%6.1f\\%%$ & $%6.1f\\%%$ & $%6.1f\\%%$ \\\\ \n", names_vec(6),   table_3_moms(6,comp_idxs));
    fprintf(loc_fileID, "\\hline \n");
    fclose(loc_fileID);

%% Table 4: additional second moments
    comp_idxs = [ix_bm,ix_no_omg,ix_symm];

    % Moment Names
    names_vec = [ "$\sigma(4r_t)$", ...
                  "$\sigma(4[r_t^e - r_t])$", ...
                  "$\sigma(4[r_t^\ast - \Delta\log q_t - r_t])$", ...
                  "$\sigma(\Delta\log q_t)$", ...
                  "$\sigma(\Delta\log E_t)$", ...
                  "$\sigma(\Delta\log q_t, \Delta\log c^\ast_t - \Delta\log c_t)$" ...
                        ];
    
    % Data Values
    data_vec = [ 2.9, 33.6, 15.5, 3.8, 3.8, 0.1];
      
    % Write Unargeted Moments
    loc_fileID = fopen([tab_path, '/table_4.tex'],'w');
    fprintf(loc_fileID, "Moment & Data & Model & No $\\omega$ & $\\gamma=\\gamma^\\ast$ \\\\ \n");
    fprintf(loc_fileID, "\\hline \n");
    fprintf(loc_fileID, "%s & $%6.1f\\%%$ & $%6.1f\\%%$ & $%6.1f\\%%$ & $%6.1f\\%%$ \\\\ \n", names_vec(1),  data_vec(1), table_4_moms(1,comp_idxs));
    fprintf(loc_fileID, "%s & $%6.1f\\%%$ & $%6.1f\\%%$ & $%6.1f\\%%$ & $%6.1f\\%%$ \\\\ \n", names_vec(2),  data_vec(2), table_4_moms(2,comp_idxs));
    fprintf(loc_fileID, "%s & $%6.1f\\%%$ & $%6.1f\\%%$ & $%6.1f\\%%$ & $%6.1f\\%%$ \\\\ \n", names_vec(3),  data_vec(3), table_4_moms(3,comp_idxs));
    fprintf(loc_fileID, "\\hline \n");
    fprintf(loc_fileID, "%s & $%6.1f\\%%$ & $%6.1f\\%%$ & $%6.1f\\%%$ & $%6.1f\\%%$ \\\\ \n", names_vec(4),  data_vec(4), table_4_moms(4,comp_idxs));
    fprintf(loc_fileID, "%s & $%6.1f\\%%$ & $%6.1f\\%%$ & $%6.1f\\%%$ & $%6.1f\\%%$ \\\\ \n", names_vec(5),  data_vec(5), table_4_moms(5,comp_idxs));
    fprintf(loc_fileID, "\\hline \n");
    fprintf(loc_fileID, "%s & $%6.2f$     & $%6.2f$     & $%6.2f$     & $%6.2f$     \\\\ \n", names_vec(6),  data_vec(6), table_4_moms(6,comp_idxs));
    fprintf(loc_fileID, "\\hline \n");
    fclose(loc_fileID);

%% Table 5: output volatility
    comp_idxs = [ix_bm,ix_no_omg,ix_symm];
    % Moment Names
    names_vec = [   "$\sigma(\Delta\log y_t)$", ...
                    "$\sigma(\Delta\log y^\ast_t)$" ...
                    ];
    
    % Data Values
    data_vec = [ 0.59, 0.81];
      
    % Write Unargeted Moments
    loc_fileID = fopen([tab_path, '/table_5.tex'],'w');
    fprintf(loc_fileID, "Moment & Data & Model & No $\\omega$ & $\\gamma=\\gamma^\\ast$ \\\\ \n");
    fprintf(loc_fileID, "\\hline \n");
    fprintf(loc_fileID, "%s & $%6.2f\\%%$ & $%6.2f\\%%$ & $%6.2f\\%%$ & $%6.2f\\%%$ \\\\ \n", names_vec(1),  data_vec(1), table_5_moms(1,comp_idxs));
    fprintf(loc_fileID, "%s & $%6.2f\\%%$ & $%6.2f\\%%$ & $%6.2f\\%%$ & $%6.2f\\%%$ \\\\ \n", names_vec(2),  data_vec(2), table_5_moms(2,comp_idxs));
    fprintf(loc_fileID, "\\hline \n");
    fclose(loc_fileID);

    
%% Table 6: nfa vol
    % Moment Names
    names_vec = [   "$\sigma((\Delta nfa_t)/y_t)$", ...
                    "$\sigma(nx_t/y_t)$", ...
                    "$\sigma((\Delta nfa_t - nx_t)/y_t)$" ...
                    "$\Delta nfa/y$", ...
                    "$nx/y$", ...
                    "$(\Delta nfa - nx)/y$" ...
                    ];
    
    % Data Values
    data_vec = [ 11.0, 1.0, 10.9, -2.8, -3.2, 0.4];
    
    loc_fileID = fopen([tab_path, '/table_6.tex'],'w');
    fprintf(loc_fileID, "Moment & Data & Model & No $\\omega$ & $\\gamma=\\gamma^\\ast$ \\\\ \n");
    fprintf(loc_fileID, "\\hline \n");
    fprintf(loc_fileID, "%s & $%6.1f\\%%$ & $%6.1f\\%%$ & $%6.1f\\%%$ & $%6.1f\\%%$ \\\\ \n", names_vec(1),  data_vec(1), table_6_moms(1,comp_idxs));
    fprintf(loc_fileID, "%s & $%6.1f\\%%$ & $%6.1f\\%%$ & $%6.1f\\%%$ & $%6.1f\\%%$ \\\\ \n", names_vec(2),  data_vec(2), table_6_moms(2,comp_idxs));
    fprintf(loc_fileID, "%s & $%6.1f\\%%$ & $%6.1f\\%%$ & $%6.1f\\%%$ & $%6.1f\\%%$ \\\\ \n", names_vec(3),  data_vec(3), table_6_moms(3,comp_idxs));
    fprintf(loc_fileID, "\\hline \n");
    fprintf(loc_fileID, "%s & $%6.1f\\%%$ & $%6.1f\\%%$ & $%6.1f\\%%$ & $%6.1f\\%%$ \\\\ \n", names_vec(4),  data_vec(4), table_6_moms(4,comp_idxs));
    fprintf(loc_fileID, "%s & $%6.1f\\%%$ & $%6.1f\\%%$ & $%6.1f\\%%$ & $%6.1f\\%%$ \\\\ \n", names_vec(5),  data_vec(5), table_6_moms(5,comp_idxs));
    fprintf(loc_fileID, "%s & $%6.1f\\%%$ & $%6.1f\\%%$ & $%6.1f\\%%$ & $%6.1f\\%%$ \\\\ \n", names_vec(6),  data_vec(6), table_6_moms(6,comp_idxs));
    fprintf(loc_fileID, "\\hline \n");
    fclose(loc_fileID);


%% Table 7: external adjustment
    % Moment Names
    names_vec = [   "$Cov\left(-(\mathbb{E}_t - \mathbb{E}_{t-1})\sum_{h=1}^{500} \left(\prod_{i=1}^{h} \frac{1}{1+r_{t+i}^k}\right)nx_{t+h},(\mathbb{E}_t - \mathbb{E}_{t-1})nfa_t\right)$", ...
                    "$Cov\left(-(\mathbb{E}_t - \mathbb{E}_{t-1})\sum_{h=1}^{500} \left(\prod_{i=1}^{h} \frac{1}{1+r_{t+i}^k}\right)val_{t+h},(\mathbb{E}_t - \mathbb{E}_{t-1})nfa_t\right)$", ...
                    "$Cov\left((\mathbb{E}_t - \mathbb{E}_{t-1})\left(\prod_{i=1}^{500} \frac{1}{1+r_{t+i}^k}\right)nfa_{t+500},(\mathbb{E}_t - \mathbb{E}_{t-1})nfa_t\right)$" ...
                    ];
    
    % Data Values
    comp_idxs = [ix_bm, ix_no_omg, ix_symm];
    loc_fileID = fopen([tab_path, '/table_7.tex'],'w');
    fprintf(loc_fileID, "  & Model  & No $\\omega$ & $\\gamma=\\gamma^\\ast$ \\\\ \\hline \n");
    fprintf(loc_fileID, "\\emph{As share of} $Var\\left((\\mathbb{E}_t - \\mathbb{E}_{t-1})nfa_t\\right)$: & & \\\\");
    fprintf(loc_fileID, "%s & $%6.1f\\%%$ & $%6.1f\\%%$ & $%6.1f\\%%$ \\\\ \n", names_vec(1),  table_7_moms(1,comp_idxs));
    fprintf(loc_fileID, "%s & $%6.1f\\%%$ & $%6.1f\\%%$ & $%6.1f\\%%$ \\\\ \n", names_vec(2),  table_7_moms(2,comp_idxs));
    fprintf(loc_fileID, "%s & $%6.1f\\%%$ & $%6.1f\\%%$ & $%6.1f\\%%$ \\\\ \n", names_vec(3),  table_7_moms(6,comp_idxs));
    fprintf(loc_fileID, "\\hline \n");
    fclose(loc_fileID);

%% Table A2: external adjustment decomposition
    % Moment Names
    names_vec = [   "$Cov\left(-(\mathbb{E}_t - \mathbb{E}_{t-1})\sum_{h=1}^{500} \left(\prod_{i=1}^{h} \frac{1}{1+r_{t+i}^k}\right)nx_{t+h},(\mathbb{E}_t - \mathbb{E}_{t-1})nfa_t\right)$", ...
                    "$Cov\left(-(\mathbb{E}_t - \mathbb{E}_{t-1})\sum_{h=1}^{500} \left(\prod_{i=1}^{h} \frac{1}{1+r_{t+i}^k}\right)val_{t+h},(\mathbb{E}_t - \mathbb{E}_{t-1})nfa_t\right)$", ...
                    "$Cov\left(-(\mathbb{E}_t - \mathbb{E}_{t-1})\sum_{h=1}^{500} \left(\prod_{i=1}^{h} \frac{1}{1+r_{t+i}^k}\right)val^r_{t+h},(\mathbb{E}_t - \mathbb{E}_{t-1})nfa_t\right)$", ...
                    "$Cov\left(-(\mathbb{E}_t - \mathbb{E}_{t-1})\sum_{h=1}^{500} \left(\prod_{i=1}^{h} \frac{1}{1+r_{t+i}^k}\right)val^{r^\ast}_{t+h},(\mathbb{E}_t - \mathbb{E}_{t-1})nfa_t\right)$", ...
                    "$Cov\left(-(\mathbb{E}_t - \mathbb{E}_{t-1})\sum_{h=1}^{500} \left(\prod_{i=1}^{h} \frac{1}{1+r_{t+i}^k}\right)val^s_{t+h},(\mathbb{E}_t - \mathbb{E}_{t-1})nfa_t\right)$", ...
                    "$Cov\left((\mathbb{E}_t - \mathbb{E}_{t-1})\left(\prod_{i=1500200} \frac{1}{1+r_{t+i}^k}\right)nfa_{t+500},(\mathbb{E}_t - \mathbb{E}_{t-1})nfa_t\right)$" ...
                    ];
    
    % Data Values
    comp_idxs = [ix_bm, ix_no_omg, ix_symm];
    loc_fileID = fopen([tab_path, '/table_A2.tex'],'w');
    fprintf(loc_fileID, "  & Model  & No $\\omega$ & $\\gamma=\\gamma^\\ast$ \\\\ \\hline \n");
    fprintf(loc_fileID, "\\emph{As share of} $Var\\left((\\mathbb{E}_t - \\mathbb{E}_{t-1})nfa_t\\right)$: & & \\\\");
    fprintf(loc_fileID, "%s & $%6.1f\\%%$ & $%6.1f\\%%$ & $%6.1f\\%%$ \\\\ \n", names_vec(1),  table_7_moms(1,comp_idxs));
    fprintf(loc_fileID, "%s & $%6.1f\\%%$ & $%6.1f\\%%$ & $%6.1f\\%%$ \\\\ \n", names_vec(2),  table_7_moms(2,comp_idxs));
    fprintf(loc_fileID, "%s & $%6.1f\\%%$ & $%6.1f\\%%$ & $%6.1f\\%%$ \\\\ \n", names_vec(3),  table_7_moms(3,comp_idxs));
    fprintf(loc_fileID, "%s & $%6.1f\\%%$ & $%6.1f\\%%$ & $%6.1f\\%%$ \\\\ \n", names_vec(4),  table_7_moms(4,comp_idxs));
    fprintf(loc_fileID, "%s & $%6.1f\\%%$ & $%6.1f\\%%$ & $%6.1f\\%%$ \\\\ \n", names_vec(5),  table_7_moms(5,comp_idxs));   
    fprintf(loc_fileID, "%s & $%6.1f\\%%$ & $%6.1f\\%%$ & $%6.1f\\%%$ \\\\ \n", names_vec(6),  table_7_moms(6,comp_idxs));
    fprintf(loc_fileID, "\\hline \n");
    fclose(loc_fileID);


%% Table 8: swap lines
 
    comp_idxs = [ix_bm];
    loc_fileID = fopen([tab_path, '/table_8.tex'],'w');
    fprintf(loc_fileID, " \\emph{Impact effects} & & &\\\\ \n");
    fprintf(loc_fileID, " $\\log E_t$ & $%+.0fbp$ & $%+.0fbp$ & $%+.0fbp$ \\\\ \n", -72, table_8_moms(1,:,comp_idxs));
    fprintf(loc_fileID, " $\\log P_t r_t^e$ &  $%+.0fbp$& $%+.0fbp$& $%+.0fbp$ \\\\  \n", 151, table_8_moms(2,:,comp_idxs));
    fprintf(loc_fileID, " $\\Delta nfa_t/y_t$ & & $%+.0fbp$& $%+.0fbp$ \\\\ \n", table_8_moms(8,:,comp_idxs));
    fprintf(loc_fileID, " $\\Delta(nfa_t-nx_t)/y_t$ & & $%+.0fbp$& $%+.0fbp$ \\\\ \\hline \n", table_8_moms(9,:,comp_idxs));
    fprintf(loc_fileID, " \\emph{Peak effects} & \\\\ \n");
    fprintf(loc_fileID, " $\\log y_t$ & & $%+.0fbp$& $%+.0fbp$\\\\ \n", table_8_moms(3,:,comp_idxs));
    fprintf(loc_fileID, " $\\log y_t^*$ & & $%+.0fbp$& $%+.0fbp$ \\\\ \\hline \n", table_8_moms(4,:,comp_idxs) );
    fclose(loc_fileID);
    

%% Table 10

    comp_idxs = [ix_no_omg_symm, ix_no_omg, ix_nocorr_nobg, ix_nocorr, ix_bm];
    loc_fileID = fopen([tab_path, '/table_10.tex'],'w');    
    fprintf(loc_fileID, "$\\gamma$ & $=\\gamma^*$ & Model & Model & Model & Model \\\\ \n");
    fprintf(loc_fileID, "$\\sigma^{\\omega}$ & 0 & 0 & Model & Model & Model \\\\ \n");
    fprintf(loc_fileID, "$b_{H,s}^g$ & n/a  & n/a & 0 & Model & Model \\\\ \n");
    fprintf(loc_fileID, "$\\rho^{p,\\omega}$ & n/a & n/a & 0 & 0 & Model \\\\ \\hline \n");
    fprintf(loc_fileID, "$k/a$   & $%6.2f\\%%$ &  $%6.2f\\%%$ &  $%6.2f\\%%$ &  $%6.2f\\%%$ &  $%6.2f\\%%$\\\\ \n", table_10_moms(1,comp_idxs));
    fprintf(loc_fileID, "$b_H/a$ & $%6.2f\\%%$ &  $%6.2f\\%%$ &  $%6.2f\\%%$ &  $%6.2f\\%%$ &  $%6.2f\\%%$\\\\ \n", table_10_moms(2,comp_idxs));
    fprintf(loc_fileID, "$b_F/a$ & $%6.2f\\%%$ &  $%6.2f\\%%$ &  $%6.2f\\%%$ &  $%6.2f\\%%$ &  $%6.2f\\%%$\\\\ \\hline \n", table_10_moms(3,comp_idxs));
    fprintf(loc_fileID, "$\\rho_t(r_{t+1}^* - \\Delta \\log q_{t+1} - r_{t+1},\\log m_{t,{t+1}})$ & $%6.2f$ &  $%6.2f$ &  $%6.2f$ &  $%6.2f$ &  $%6.2f$\\\\ \n", table_10_moms(4,comp_idxs));
    fprintf(loc_fileID, "$\\rho_t(r_{t+1}^* - \\Delta \\log q_{t+1} - r_{t+1},\\log m_{t,{t+1}}^* + \\Delta \\log q_{t+1})$ & $%6.2f$ &  $%6.2f$ &  $%6.2f$ &  $%6.2f$ &  $%6.2f$\\\\ \\hline \n", table_10_moms(5,comp_idxs));
    fclose(loc_fileID);

